echo "test1.json for package A (task example):"
./dependency_resolver "test1.json" "A"
echo ""
echo ""
echo "test2.json for package D:"
./dependency_resolver "test2.json" "D"
echo ""
echo ""
echo "test3.json for package A (circular dependency):"
./dependency_resolver "test3.json" "A"
echo ""
echo ""